print('=====Desafio 004=====')

n= input("Digite algo: ")
#n1=n.isdecimal()
#n2=n.isspace()
#n3=n.islower()
#n4=n.isalpha()
#n5=type(n)
#n6=n.isalnum()
#n7=n.isupper()
#n8=n.istitle()

print(' O tipo primitivo desse valor é : ', type(n))
print('Só tem espaços?', n.isspace())
print('É um número?', n.isdecimal())
print('É alfabético? ', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('Está em maiúsculas? ', n.isupper())
print('Está em minúsculas?', n.islower())
print('Está capitalizada?', n.istitle())

